"""Add tables

Revision ID: cf1fc2871a71
Revises: 3ccaf8badb52
Create Date: 2025-01-31 17:35:04.190665

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cf1fc2871a71"
down_revision: Union[str, None] = "3ccaf8badb52"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f("uq_building_uuid"), "building", ["uuid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_building_uuid"), "building", type_="unique")
    # ### end Alembic commands ###
