"""Add index on accessibility_id in building

Revision ID: 4d8762f4b5dc
Revises: 3871f2b24d5c
Create Date: 2025-02-10 19:26:26.640233

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4d8762f4b5dc"
down_revision: Union[str, None] = "3871f2b24d5c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_building_activity_id"), "building", ["activity_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_building_activity_id"), table_name="building")
    # ### end Alembic commands ###
