"""Define srid on gps_coord colmun in building table

Revision ID: 5a8bdb7ed878
Revises: 4d8762f4b5dc
Create Date: 2025-02-11 16:03:58.653528

"""

from typing import Sequence, Union

import geoalchemy2
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5a8bdb7ed878"
down_revision: Union[str, None] = "4d8762f4b5dc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "building",
        "gps_coord",
        existing_type=geoalchemy2.types.Geometry(
            geometry_type="POINT",
            from_text="ST_GeomFromEWKT",
            name="geometry",
            _spatial_index_reflected=True,
        ),
        type_=geoalchemy2.types.Geometry(
            geometry_type="POINT",
            srid=4326,
            spatial_index=False,
            from_text="ST_GeomFromEWKT",
            name="geometry",
        ),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "building",
        "gps_coord",
        existing_type=geoalchemy2.types.Geometry(
            geometry_type="POINT",
            srid=4326,
            spatial_index=False,
            from_text="ST_GeomFromEWKT",
            name="geometry",
        ),
        type_=geoalchemy2.types.Geometry(
            geometry_type="POINT",
            from_text="ST_GeomFromEWKT",
            name="geometry",
            _spatial_index_reflected=True,
        ),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
