"""Fix relationship def

Revision ID: 11cf88f1901b
Revises: 8edcb512bd51
Create Date: 2025-02-10 11:33:51.038023

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "11cf88f1901b"
down_revision: Union[str, None] = "8edcb512bd51"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f("uq_accessibility_id"), "accessibility", ["id"])
    op.create_unique_constraint(op.f("uq_activity_id"), "activity", ["id"])
    op.create_unique_constraint(op.f("uq_building_uuid"), "building", ["uuid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_building_uuid"), "building", type_="unique")
    op.drop_constraint(op.f("uq_activity_id"), "activity", type_="unique")
    op.drop_constraint(op.f("uq_accessibility_id"), "accessibility", type_="unique")
    # ### end Alembic commands ###
