"""correct relationship building activity

Revision ID: dfc7133408ad
Revises: a9f681c2273f
Create Date: 2025-02-05 16:54:38.145233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfc7133408ad'
down_revision: Union[str, None] = 'a9f681c2273f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_accessibility_id'), 'accessibility', ['id'])
    op.create_unique_constraint(op.f('uq_activity_id'), 'activity', ['id'])
    op.add_column('building', sa.Column('activity_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(op.f('uq_building_uuid'), 'building', ['uuid'])
    op.create_foreign_key(op.f('fk_building_activity_id_activity'), 'building', 'activity', ['activity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_building_activity_id_activity'), 'building', type_='foreignkey')
    op.drop_constraint(op.f('uq_building_uuid'), 'building', type_='unique')
    op.drop_column('building', 'activity_id')
    op.drop_constraint(op.f('uq_activity_id'), 'activity', type_='unique')
    op.drop_constraint(op.f('uq_accessibility_id'), 'accessibility', type_='unique')
    # ### end Alembic commands ###
