"""Add index on accessibility and activity

Revision ID: 3871f2b24d5c
Revises: 87e9f06e2dcc
Create Date: 2025-02-10 15:55:36.103438

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3871f2b24d5c"
down_revision: Union[str, None] = "87e9f06e2dcc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_accessibility_building_id", "accessibility", type_="unique")
    op.create_index(
        op.f("ix_accessibility_building_id"),
        "accessibility",
        ["building_id"],
        unique=True,
    )
    op.drop_constraint("uq_activity_id", "activity", type_="unique")
    op.create_index(op.f("ix_activity_id"), "activity", ["id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_activity_id"), table_name="activity")
    op.create_unique_constraint("uq_activity_id", "activity", ["id"])
    op.drop_index(op.f("ix_accessibility_building_id"), table_name="accessibility")
    op.create_unique_constraint(
        "uq_accessibility_building_id", "accessibility", ["building_id"]
    )
    # ### end Alembic commands ###
