"""Init accesmap tables Building, Acessibility, Activity

Revision ID: 8edcb512bd51
Revises:
Create Date: 2025-02-07 10:43:40.144740

"""

from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8edcb512bd51"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=256), nullable=True),
        sa.Column("icon_name", sa.String(length=256), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activity")),
        sa.UniqueConstraint("id", name=op.f("uq_activity_id")),
        sa.UniqueConstraint("name", name=op.f("uq_activity_name")),
    )
    op.create_table(
        "building",
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=True),
        sa.Column("postal_code", sa.Integer(), nullable=True),
        sa.Column("num_street", sa.String(length=256), nullable=True),
        sa.Column("street", sa.String(length=256), nullable=True),
        sa.Column("city", sa.String(length=256), nullable=True),
        sa.Column("contact_url", sa.String(length=256), nullable=True),
        sa.Column("website_url", sa.String(length=256), nullable=True),
        sa.Column(
            "gps_coord",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column("activity_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activity.id"],
            name=op.f("fk_building_activity_id_activity"),
        ),
        sa.PrimaryKeyConstraint("uuid", name=op.f("pk_building")),
        sa.UniqueConstraint("uuid", name=op.f("uq_building_uuid")),
    )
    op.create_index(
        "idx_centre_gps_coord",
        "building",
        ["gps_coord"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_table(
        "accessibility",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("building_id", sa.String(), nullable=True),
        sa.Column("transport_station_presence", sa.Boolean(), nullable=True),
        sa.Column("stationnement_presence", sa.Boolean(), nullable=True),
        sa.Column("stationnement_pmr", sa.Boolean(), nullable=True),
        sa.Column("stationnement_ext_presence", sa.Boolean(), nullable=True),
        sa.Column("stationnement_ext_pmr", sa.Boolean(), nullable=True),
        sa.Column("cheminement_ext_presence", sa.Boolean(), nullable=True),
        sa.Column("cheminement_ext_terrain_stable", sa.Boolean(), nullable=True),
        sa.Column("cheminement_ext_plain_pied", sa.Boolean(), nullable=True),
        sa.Column("cheminement_ext_ascenseur", sa.Boolean(), nullable=True),
        sa.Column("cheminement_ext_nombre_marches", sa.Integer(), nullable=True),
        sa.Column("cheminement_ext_reperage_marches", sa.Boolean(), nullable=True),
        sa.Column("cheminement_ext_sens_marches", sa.String(length=50), nullable=True),
        sa.Column("cheminement_ext_main_courante", sa.Boolean(), nullable=True),
        sa.Column("cheminement_ext_rampe", sa.String(length=50), nullable=True),
        sa.Column("cheminement_ext_pente_presence", sa.Boolean(), nullable=True),
        sa.Column(
            "cheminement_ext_pente_degre_difficulte", sa.String(length=50), nullable=True
        ),
        sa.Column("cheminement_ext_pente_longueur", sa.String(length=50), nullable=True),
        sa.Column("cheminement_ext_devers", sa.String(length=50), nullable=True),
        sa.Column("cheminement_ext_bande_guidage", sa.Boolean(), nullable=True),
        sa.Column("cheminement_ext_retrecissement", sa.Boolean(), nullable=True),
        sa.Column("entree_reperage", sa.Boolean(), nullable=True),
        sa.Column("entree_vitree", sa.Boolean(), nullable=True),
        sa.Column("entree_vitree_vitrophanie", sa.Boolean(), nullable=True),
        sa.Column("entree_plain_pied", sa.Boolean(), nullable=True),
        sa.Column("entree_ascenseur", sa.Boolean(), nullable=True),
        sa.Column("entree_marches", sa.Integer(), nullable=True),
        sa.Column("entree_marches_reperage", sa.Boolean(), nullable=True),
        sa.Column("entree_marches_main_courante", sa.Boolean(), nullable=True),
        sa.Column("entree_marches_rampe", sa.String(length=50), nullable=True),
        sa.Column("entree_marches_sens", sa.String(length=50), nullable=True),
        sa.Column("entree_dispositif_appel", sa.Boolean(), nullable=True),
        sa.Column("entree_dispositif_appel_type", sa.JSON(), nullable=True),
        sa.Column("entree_balise_sonore", sa.Boolean(), nullable=True),
        sa.Column("entree_aide_humaine", sa.Boolean(), nullable=True),
        sa.Column("entree_largeur_mini", sa.Integer(), nullable=True),
        sa.Column("entree_pmr", sa.Boolean(), nullable=True),
        sa.Column("entree_porte_presence", sa.Boolean(), nullable=True),
        sa.Column("entree_porte_manoeuvre", sa.String(length=50), nullable=True),
        sa.Column("entree_porte_type", sa.String(length=50), nullable=True),
        sa.Column("accueil_visibilite", sa.Boolean(), nullable=True),
        sa.Column("accueil_personnels", sa.String(length=50), nullable=True),
        sa.Column("accueil_audiodescription_presence", sa.Boolean(), nullable=True),
        sa.Column("accueil_audiodescription", sa.JSON(), nullable=True),
        sa.Column(
            "accueil_equipements_malentendants_presence", sa.Boolean(), nullable=True
        ),
        sa.Column("accueil_equipements_malentendants", sa.JSON(), nullable=True),
        sa.Column("accueil_cheminement_plain_pied", sa.Boolean(), nullable=True),
        sa.Column("accueil_cheminement_ascenseur", sa.Boolean(), nullable=True),
        sa.Column("accueil_cheminement_nombre_marches", sa.Integer(), nullable=True),
        sa.Column("accueil_cheminement_reperage_marches", sa.Boolean(), nullable=True),
        sa.Column("accueil_cheminement_main_courante", sa.Boolean(), nullable=True),
        sa.Column("accueil_cheminement_rampe", sa.String(length=50), nullable=True),
        sa.Column(
            "accueil_cheminement_sens_marches", sa.String(length=50), nullable=True
        ),
        sa.Column("accueil_chambre_nombre_accessibles", sa.Integer(), nullable=True),
        sa.Column("accueil_chambre_douche_plain_pied", sa.Boolean(), nullable=True),
        sa.Column("accueil_chambre_douche_siege", sa.Boolean(), nullable=True),
        sa.Column("accueil_chambre_douche_barre_appui", sa.Boolean(), nullable=True),
        sa.Column("accueil_chambre_sanitaires_barre_appui", sa.Boolean(), nullable=True),
        sa.Column("accueil_chambre_sanitaires_espace_usage", sa.Boolean(), nullable=True),
        sa.Column("accueil_chambre_numero_visible", sa.Boolean(), nullable=True),
        sa.Column("accueil_chambre_equipement_alerte", sa.Boolean(), nullable=True),
        sa.Column("accueil_chambre_accompagnement", sa.Boolean(), nullable=True),
        sa.Column("accueil_retrecissement", sa.Boolean(), nullable=True),
        sa.Column("sanitaires_presence", sa.Boolean(), nullable=True),
        sa.Column("sanitaires_adaptes", sa.Boolean(), nullable=True),
        sa.Column("labels", sa.JSON(), nullable=True),
        sa.Column("labels_familles_handicap", sa.JSON(), nullable=True),
        sa.Column("conformite", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["building_id"],
            ["building.uuid"],
            name=op.f("fk_accessibility_building_id_building"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_accessibility")),
        sa.UniqueConstraint("building_id", name=op.f("uq_accessibility_building_id")),
        sa.UniqueConstraint("id", name=op.f("uq_accessibility_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("accessibility")
    op.drop_index("idx_centre_gps_coord", table_name="building", postgresql_using="gist")
    op.drop_table("building")
    op.drop_table("activity")
    # ### end Alembic commands ###
