"""Init tables

Revision ID: ee3e4624ce0d
Revises: 
Create Date: 2025-02-03 17:29:54.321050

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ee3e4624ce0d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_centre_gps_coord', table_name='building', postgresql_using='gist')
    op.drop_table('building')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('building',
    sa.Column('uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('gps_coord', sa.NullType(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('uuid', name='pk_building'),
    sa.UniqueConstraint('uuid', name='uq_building_uuid')
    )
    op.create_index('idx_centre_gps_coord', 'building', ['gps_coord'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###
