"""Add tables

Revision ID: 3ccaf8badb52
Revises:
Create Date: 2025-01-31 16:10:27.630385

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = "3ccaf8badb52"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "building",
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=True),
        sa.Column(
            "gps_coord",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("uuid", name=op.f("pk_building")),
        sa.UniqueConstraint("uuid", name=op.f("uq_building_uuid")),
    )
    op.create_index(
        "idx_centre_gps_coord",
        "building",
        ["gps_coord"],
        unique=False,
        postgresql_using="gist",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_centre_gps_coord", table_name="building", postgresql_using="gist")
    op.drop_table("building")
    # ### end Alembic commands ###
