"""Add index on building uuid

Revision ID: 87e9f06e2dcc
Revises: 11cf88f1901b
Create Date: 2025-02-10 15:38:24.894820

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "87e9f06e2dcc"
down_revision: Union[str, None] = "11cf88f1901b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_building_uuid", "building", type_="unique")
    op.create_index(op.f("ix_building_uuid"), "building", ["uuid"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_building_uuid"), table_name="building")
    op.create_unique_constraint("uq_building_uuid", "building", ["uuid"])
    # ### end Alembic commands ###
