mapping_activity_icon = {
    "Agence immobilière": "building",
    "Hôtel": "hotel",
    "Vêtements": "tshirt",
    "Soins de beauté, esthétique": "spa",
    "Café, bar, brasserie": "coffee",
    "Restauration rapide": "hamburger",
    "Achat or": "gem",
    "Auto école": "car",
    "Salle des fêtes": "users",
    "Boucherie / commerce de viande": "drumstick-bite",
    "Commerce": "store",
    "Coiffure": "cut",
    "Fleuriste": "flower",
    "Crèmerie Fromagerie": "cheese",
    "Chambre d'hôtes, gîte, pension, meublé de tourisme": "bed",
    "Vente de matériel et équipement industriels": "cogs",
    "Électroménager et matériel audio-vidéo": "tv",
    "Droguerie": "broom",
    "Herboristerie naturopathie": "leaf",
    "Boulangerie Pâtisserie": "bread-slice",
    "Photographie": "camera",
    "Magasin de cbd": "cannabis",
    "Bijouterie fantaisie": "gem",
    "Bijouterie joaillerie": "ring",
    "Parfumerie, cosmétique": "perfume",
    "Chaussures": "shoe-prints",
    "Banques, caisses d'épargne": "university",
    "Chocolatier": "candy-cane",
    "Commerce automobile": "car",
    "Opticien": "glasses",
    "Garage automobile": "wrench",
    "Vente d'articles de sport": "futbol",
    "Agence de travail temporaire": "briefcase",
    "Jeux vidéo": "gamepad",
    "Restaurant": "utensils",
    "Centre culturel": "landmark",
    "Barbier": "cut",
    "Agence matrimoniale": "heart",
    "Discothèque": "music",
    "Théâtre": "theater-masks",
    "Coworking": "users",
    "Collège": "school",
    "Sports et loisirs": "bicycle",
    "Art, centre d'art": "palette",
    "Jardinerie": "seedling",
    "Carrosserie": "car-repair",
    "Institut de formation": "graduation-cap",
    "Hôpital": "hospital",
    "Animalerie": "paw",
    "Accessoires": "cogs",
    "Artisanat": "tools",
    "Bien-être": "heartbeat",
    "Informatique": "laptop",
    "Massages": "hand-paper",
    "École maternelle": "child",
    "Magasin de souvenirs": "gift",
    "Piscine, centre aquatique": "swimmer",
    "Traiteur": "utensils",
    "Jeux jouets": "toys",
    "Vétérinaire": "stethoscope",
    "Association": "users",
    "Chirurgien dentiste": "tooth",
    "Salle de spectacle": "ticket-alt",
    "Tatouage Piercing": "paint-brush",
    "Office du tourisme": "sun",
    "Centre d’information et d’orientation": "info-circle",
    "Psychologie, Psychiatrie": "brain",
    "Notaire": "gavel",
    "Concessionnaire automobile": "car",
    "Ehpad": "bed",
    "Bowling": "bowling-ball",
    "Cimetière": "cross",
    "Librairie": "book",
    "Laboratoire d'analyse médicale": "flask",
    "Antiquaire": "archive",
    "Décoration Design": "paint-roller",
    "Cinéma": "film",
    "Imprimerie photocopie reliure": "print",
    "Pompes funèbres": "coffin",
    "Poterie verrerie céramique": "mug-hot",
    "Salle de danse": "dance",
    "Aménagement maison : cuisine salle de bain salon": "couch",
    "Emploi, formation": "briefcase",
    "Parking & stationnement": "parking",
    "Meubles ameublement": "couch",
    "Centre national de la fonction publique territoriale": "building",
    "Immobilier": "home",
    "Assurance": "shield-alt",
    "Achat, vente, réparation de matériel informatique et téléphonique": "mobile-alt",
    "Motocycle vente et entretien": "motorcycle",
    "Espace numérique": "desktop",
    "Toilettes publiques": "toilet",
    "Bibliothèque médiathèque": "book-reader",
    "Galerie d'art": "palette",
    "Vente de cafés et thés": "coffee",
    "Salon de thé": "tea",
    "Université ou école supérieure": "university",
    "Agence de voyage": "plane-departure",
    "Centre médical": "hospital",
    "Autre": "question-circle",
    "Cycle vente et entretien": "bicycle",
    "Réparation auto et de matériel agricole": "tools",
    "Instruments et matériel de musique": "guitar",
    "Supérette": "store",
    "Plomberie, chauffage": "wrench",
    "Pharmacie": "capsules",
    "Musée": "museum",
    "Stade": "football-ball",
    "Epicerie fine": "shopping-basket",
    "Épicerie": "cart-plus",
    "Revêtements murs et sols": "paint-roller",
    "Bricolage, matériaux, travaux": "hammer",
    "Gymnase": "futbol",
    "Toiletteur": "paw",
    "Pressing, nettoyage": "tshirt",
    "Blanchisserie teinturerie": "tint",
    "Contrôle technique auto": "cogs",
    "Hôtel restaurant": "utensils",
    "Résidence de tourisme": "bed",
    "Salle de remise en forme": "dumbbell",
    "Administration publique": "building",
    "Supermarché": "store",
    "Ostéopathie": "user-md",
    "Association aide aux victimes": "heart",
    "Laverie": "bath",
    "Service ou aide à domicile": "home",
    "Vente de matériel médical": "heartbeat",
    "Crèche": "baby-carriage",
    "Centre d'examen": "pencil-alt",
    "Location véhicules": "car",
    "Brocante": "archive",
    "Organisme de conseil": "comments",
    "Services techniques": "wrench",
    "Cigarette électronique": "smoking",
    "Archives": "archive",
    "Lieu de visite": "map-marker-alt",
    "Lieu de culte": "pray",
    "Monument historique": "landmark",
    "Centre religieux": "praying-hands",
    "Confiserie": "candy-cane",
    "Électricien": "plug",
    "Hypnothérapeute": "user-injured",
    "Aide sociale à l'enfance : action éducative": "users",
    "Conservatoire et école de musique": "music",
    "Station service": "gas-pump",
    "Géomètre": "compass",
    "Espace vert et naturel": "tree",
    "Cordonnerie serrurerie": "key",
    "Ambulances": "ambulance",
    "Centre de vacances": "sun",
    "Orthopédie": "bone",
    "Distribution spécialisée / commerce de gros": "cogs",
    "Horlogerie": "clock",
    "Vente de matériel pour piscine": "swimmer",
    "Club de sport": "futbol",
    "Centre de loisirs": "leaf",
    "Salle multisports": "basketball-ball",
    "Centre équestre": "horse",
    "Établissement militaire": "flag-checkered",
    "Audio prothésiste": "ear",
    "Oenotourisme": "wine-glass",
    "Comptable expert-comptable": "calculator",
    "Organisation patronale, professionnelle, syndicale": "users-cog",
    "Téléphonie": "mobile-alt",
    "Maroquinerie sellerie articles de voyage": "suitcase",
    "Location articles loisirs et sport": "bicycle",
    "Radiodiagnostic et imagerie médicale": "x-ray",
    "Maison de santé ou centre de santé": "clinic-medical",
    "Ophtalmologie": "eye",
    "Bâtiment d'accueil": "building",
    "Circuit sportif deux roues / voiture": "car",
    "Charcuterie": "bacon",
    "Guichet france services": "id-card",
    "Salle de concert": "headphones",
    "Centre social": "users",
    "Accrobranche": "tree",
    "Personnes âgées : hébergement": "bed",
    "École élémentaire": "school",
    "Information Touristique": "info-circle",
    "Avocat": "gavel",
    "Courtier": "briefcase",
    "Menuiserie, ébénisterie": "cogs",
    "Espace collaboratif": "users-cog",
    "Architecte": "building",
    "Sécurité sociale, mutuelle santé": "medkit",
    "Ferme": "tractor",
    "Spa": "spa",
    "Bazar": "cogs",
    "Parc d’attraction": "ferris-wheel",
    "Retouche": "scissors",
    "Location de matériels": "wrench",
    "Équipements du foyer": "couch",
    "Centre commercial": "shopping-center",
    "Syndic, gérance immo": "building",
    "Clinique": "clinic-medical",
    "Friperie": "tshirt",
    "Primeur": "apple-alt",
    "Établissement de santé": "hospital",
    "Autres établissements pour adultes et familles en difficulté": "users",
    "Puériculture": "baby-carriage",
    "Aéroport, aérodrome": "plane",
    "Agence de publicité": "bullhorn",
    "Loisirs créatifs": "paint-brush",
    "Construction, rénovation": "hammer",
    "Salle de jeux": "gamepad",
    "Accompagnement personnes agees": "users",
    "Résidence, foyer": "home",
    "Equipement sportif": "football-ball",
    "Masseur kinésithérapeute": "user-md",
    "Centre de vaccination": "syringe",
    "Disquaire": "record-vinyl",
    "Caviste / commerce de détail de boissons": "wine-bottle",
    "Bureau de poste": "mail-bulk",
    "Sophrologue": "user-injured",
    "Numérique": "laptop",
    "Agence départementale d'information sur le logement": "info-circle",
    "Centre de ressources et d'information": "book",
    "Papeterie, presse, journaux": "newspaper",
    "Collectivité territoriale": "building",
    "Transport": "bus",
    "Vente à distance": "shopping-cart",
    "Bailleur social": "building",
    "Agence événementielle": "calendar-check",
    "Salle spécialisée": "theater-masks",
    "Mairie": "city",
    "Oto-rhino-laryngologie": "ear-listen",
    "Point information jeunesse": "info",
    "Pédicure-podologue": "shoe-prints",
    "Ressourcerie": "recycle",
    "Village de vacances": "campground",
    "Commerce bio": "leaf",
    "Gare sncf": "train",
    "Camping caravaning": "campground",
    "Boulodrome": "bowling-ball",
    "Plateaux et terrains de jeux extérieurs": "play-circle",
    "Parc": "tree",
    "Bar tabac": "cocktail",
    "Tabac": "smoke",
    "Glacier": "ice-cream",
    "Arts de la table": "utensils",
    "Hypermarché": "store",
    "Station lavage auto": "car-wash",
    "Lingerie sous-vêtements": "tshirt",
    "Produits de terroir": "leaf",
    "Déchetterie": "trash",
    "Dermatologie vénéréologie": "skin",
    "Taxi": "taxi",
    "Literie": "bed",
    "Traduction et interprétation": "language",
    "Auberge de jeunesse, centre international de séjour": "bed",
    "Sage-femme": "user-nurse",
    "Magasin de bois de chauffage": "fire",
    "Luminaire": "lightbulb",
    "Sports nautiques": "water",
    "Salle de réunion ou réception": "users",
    "Salle non spécialisée": "cogs",
    "Armurerie coutellerie": "crosshairs",
    "Ecole de ski et snowboard": "snowboarding",
    "Boutique de mariage": "gift",
    "Opéra": "theater-masks",
    "Médecin généraliste": "user-md",
    "Médecine du travail": "briefcase-medical",
    "Salle de combat": "fist-raised",
    "Tribunal": "gavel",
    "Orthoptie": "eye",
    "Etablissement pénitentiaire": "lock",
    "École primaire (regroupement maternelle et élémentaire)": "school",
    "Matériel de pêche": "fish",
    "Aquarium": "fish",
    "Thalassothérapie": "spa",
    "Mercerie": "scissors",
    "Arène": "cogs",
    "Produits surgelés": "ice-cream",
    "Rempailleur tapissier chaises fauteuils": "couch",
    "Encadreur enlumineur": "paint-brush",
    "Magasin de tissus": "tshirt",
    "Kiosque (théâtre, pizza, journaux)": "newspaper",
    "Cyclisme": "bicycle",
    "Evénement culturel": "calendar-alt",
    "Jardin botanique et/ou zoologique": "leaf",
    "Tiers lieu": "users-cog",
    "Observatoire, astronomie": "star",
    "Chapeaux et couvre-chefs": "hat-cowboy",
    "Musique": "music",
    "Apiculteur": "honey-pot",
    "Biscuiterie": "cookie",
    "Athlétisme": "running",
    "Ergothérapeute": "user-injured",
    "Location saisonnière": "home",
    "Fruits et légumes": "apple-alt",
    "Poissonnerie / commerce de poissons, crustacés et mollusques": "fish",
    "Ecole de danse": "dance",
    "Auditorium et salle de conférence": "microphone",
    "Textile hors habillement": "tshirt",
    "Produits d'occasion": "recycle",
    "Psychomotricien": "brain",
    "Ordre des avocats": "gavel",
    "Déménageur": "truck",
    "Karaoké": "microphone-alt",
    "Infirmier": "user-nurse",
    "Casino": "casino",
    "Magasin de déguisements": "mask",
    "Plage, zone de baignade": "sun",
    "Restaurant scolaire": "utensils",
    "Soin, médecine douce": "spa",
    "Acupuncture": "user-md",
    "Rhumatologie": "bone",
    "Vitrerie, miroiterie": "glass-whiskey",
    "Cardiologie": "heartbeat",
    "Lycée": "school",
    "Coaching": "chalkboard-teacher",
    "Sex shop": "cogs",
    "Point d'information local dédié aux personnes âgées": "info-circle",
    "Pépinière": "tree",
    "Gare routière": "bus",
    "Orthodontie": "teeth",
    "Stockage": "archive",
    "Port": "ship",
    "Gendarmerie": "shield-alt",
    "Bureau de douane": "box",
    "Chambre de commerce et d'industrie": "building",
    "Maison de services au public": "hands-helping",
    "Commissariat de Police": "user-shield",
    "Huissier": "balance-scale",
    "Pneumologie": "lungs",
    "Kinésiologue": "spine",
    "Pédiatrie": "baby",
    "Gynécologie": "female",
    "Orthophonie": "ear-listen",
    "Urologie": "toilet-paper",
    "Profession libérale": "briefcase",
    "Cantine": "utensils",
    "Caisse d'allocations familiales (caf)": "money-bill-wave",
    "Point justice": "gavel",
    "Entretien de piscine": "water",
    "Château": "castle",
    "Coopérative agricole": "tractor",
    "Fédération départementale pour la pêche et la protection du milieu aquatique": "fish",
    "Bureau de change": "exchange-alt",
    "Personnes âgées : foyer restaurant": "users",
    "Garderie": "baby-carriage",
    "Centre de protection maternelle et infantile (pmi)": "baby",
    "Etablissement de prévention": "shield-alt",
    "Mission d'accueil et d'information des associations": "handshake",
    "Trésorerie": "piggy-bank",
    "Gastro-entérologie hépatologie": "liver",
    "Centre d'information sur les droits des femmes et des familles": "female",
    "Centre de gestion de la fonction publique territoriale": "cogs",
    "Établissement thermal": "water",
    "Marché": "store",
    "Chambre agriculture": "cogs",
    "Chambre metier": "tools",
    "Hébergement insolite": "campground",
    "Viticulteur": "wine-glass",
    "Patinoire": "snowflake",
    "Chirurgie": "scissors",
    "Tennis": "tennis-ball",
    "Maison départementale des personnes handicapées": "wheelchair",
    "Point accueil numerique": "laptop",
    "Enseignement culturel": "paint-brush",
    "Taxidermie": "dove",
    "Direction départementale de la protection des populations": "users-cog",
    "Neurologie": "brain",
    "Anesthésie": "syringe",
    "Endocrinologue": "flask",
    "Point conseil budget": "calculator",
    "Mission locale pour l'insertion professionnelle et sociale des jeunes": "user-graduate",
    "Parc des expositions": "building",
    "Gare tgv": "train",
    "Médiation": "handshake",
    "Garde meuble": "archive",
    "Skatepark": "skating",
    "Refuge animalier": "paw",
}
